// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfypd3RphhEGQ98RO6q81sRmPXMXIevg8',
    appId: '1:684130772443:web:9fa91155f763afb51233fe',
    messagingSenderId: '684130772443',
    projectId: 'gnml-416500',
    authDomain: 'gnml-416500.firebaseapp.com',
    storageBucket: 'gnml-416500.appspot.com',
    measurementId: 'G-5K6MF6LN9F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgqPmZBGN9LUyUCTuYNeOlpTayC1BUyAU',
    appId: '1:684130772443:android:1d0109324698466f1233fe',
    messagingSenderId: '684130772443',
    projectId: 'gnml-416500',
    storageBucket: 'gnml-416500.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApUvJBF3xmGUEWL_69g_sOZlDFoRA2Bj8',
    appId: '1:684130772443:ios:32b8eb374e0d71a51233fe',
    messagingSenderId: '684130772443',
    projectId: 'gnml-416500',
    storageBucket: 'gnml-416500.appspot.com',
    iosBundleId: 'com.example.gnml',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApUvJBF3xmGUEWL_69g_sOZlDFoRA2Bj8',
    appId: '1:684130772443:ios:9337a905197c67b71233fe',
    messagingSenderId: '684130772443',
    projectId: 'gnml-416500',
    storageBucket: 'gnml-416500.appspot.com',
    iosBundleId: 'com.example.gnml.RunnerTests',
  );
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: "AIzaSyBgqPmZBGN9LUyUCTuYNeOlpTayC1BUyAU",
    appId: "1:684130772443:android:505bb6ee00df62201233fe",
    messagingSenderId: "684130772443",
    projectId: "gnml-416500",
  );
}
